[internal]
; Llamadas internas entre extensiones
exten => 6001,1,Dial(PJSIP/6001,30)
exten => 6002,1,Dial(PJSIP/6002,30)

; Entrada al Call Center Inteligente (control por ARI / Stasis)
exten => 8000,1,NoOp(Entrando a la app ARI callcenter-app)
 same => n,Stasis(callcenter-app)
 same => n,Hangup()
