[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

; ===== Extension 6001 (Zoiper) =====
[6001]
type=endpoint
transport=transport-udp
context=internal
disallow=all
allow=ulaw,alaw
auth=auth6001
aors=6001
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[auth6001]
type=auth
auth_type=userpass
username=6001
password=6001

[6001]
type=aor
max_contacts=1
remove_existing=yes

; ===== Extension 6002 (Linphone) =====
[6002]
type=endpoint
transport=transport-udp
context=internal
disallow=all
allow=ulaw,alaw
auth=auth6002
aors=6002
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[auth6002]
type=auth
auth_type=userpass
username=6002
password=6002

[6002]
type=aor
max_contacts=1
remove_existing=yes
